# Welcome to Jekyll!

# Website settings
title: "Dean Coakley"
description: "Dean's resume and current projects"
keywords: "Dean,Coakley,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://dean-coakley.github.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Dean'
  first_name: 'Dean'
  last_name: 'Coakley'
  email: 'dean.s.coakley@gmail.com'
  github_username: 'dean-coakley'
  desc: 'I am a Software Development student in Cork Institute of Technology. I have a passion for open source software, Golang and linux'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
